/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\frames\painting_frame.glb -t -r public 
*/

import { Html, useGLTF, useTexture } from "@react-three/drei";
import { JSX, useRef, useState } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import { Data } from "../app/(exhibition)/page";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_24: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_27: THREE.Mesh;
    Object_28: THREE.Mesh;
    Object_29: THREE.Mesh;
    Object_30: THREE.Mesh;
    Object_31: THREE.Mesh;
    Object_32: THREE.Mesh;
    Object_33: THREE.Mesh;
    Object_34: THREE.Mesh;
    Object_35: THREE.Mesh;
    Object_36: THREE.Mesh;
    Object_37: THREE.Mesh;
    Object_38: THREE.Mesh;
    Object_39: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_40: THREE.Mesh;
    Object_41: THREE.Mesh;
    Object_42: THREE.Mesh;
    Object_43: THREE.Mesh;
    Object_44: THREE.Mesh;
    Object_45: THREE.Mesh;
    Object_46: THREE.Mesh;
    Object_47: THREE.Mesh;
    Object_48: THREE.Mesh;
    Object_49: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_53: THREE.Mesh;
    Object_54: THREE.Mesh;
    Object_51: THREE.Mesh;
  };
  materials: {
    ["Material.028"]: THREE.MeshStandardMaterial;
    ["Material.029"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
    painting_frame: THREE.MeshStandardMaterial;
  };
};

interface PaintingFrameProps {
  onMoveCamera?: (object: THREE.Object3D) => Promise<void>;
  onShowPanel: (item: Data) => void;
  showIcon: boolean;
  item: Data;
  mode?: string;
  isClose?: boolean;
  isOpen?: boolean;
}

export default function PaintingFrame(
  props: JSX.IntrinsicElements["group"] & PaintingFrameProps
) {
  const groupRef = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(
    "https://firebasestorage.googleapis.com/v0/b/artchain-c46a7.firebasestorage.app/o/3D-models%2Fpainting_frame.glb?alt=media&token=5b003fdd-bd8e-4313-ac5d-562ce8ab002b"
  ) as unknown as GLTFResult;
  const texture = useTexture(props.item.imageUrl);
  const octahedronGeometryRef = useRef<THREE.Mesh>(null);

  useFrame((_, delta) => {
    if (octahedronGeometryRef.current) {
      octahedronGeometryRef.current.rotation.y += delta;
      octahedronGeometryRef.current.rotation.x += delta * 0.3;
    }
  });

  return (
    <group
      {...props}
      ref={groupRef}
      dispose={null}
      //   onClick={(e) => {
      //     e.stopPropagation();
      //     if (props.onMoveCamera && groupRef.current) {
      //       props.onMoveCamera(groupRef.current);
      //     }
      //   }}
    >
      <group
        position={[0, 1.177, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.552}
        onClick={() => {
          if (props.onMoveCamera && groupRef.current) {
            props.onMoveCamera(groupRef.current);
          }
        }}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[0.001, -0.01, -0.049]}
            rotation={[0, -1.571, 0]}
            scale={0.319}
          >
            <mesh
              geometry={nodes.Object_10.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_11.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_12.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_13.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_14.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_15.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_16.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_17.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_18.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_19.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_20.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_21.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_22.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_23.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_24.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_25.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_26.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_27.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_28.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_29.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_30.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_31.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_32.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_33.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_34.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_35.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_36.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_37.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_38.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_39.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials["Material.029"]}
            />
            <mesh
              geometry={nodes.Object_40.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_41.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_42.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_43.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_44.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_45.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_46.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_47.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_48.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_49.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_5.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_6.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_7.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_8.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_9.geometry}
              material={materials["Material.028"]}
            />
          </group>
          <group
            position={[0.001, -0.01, -0.049]}
            rotation={[0, -1.571, 0]}
            scale={0.319}
          >
            <mesh
              geometry={nodes.Object_53.geometry}
              material={materials["Material.003"]}
            />
            <mesh
              geometry={nodes.Object_54.geometry}
              material={materials["Material.004"]}
            />
          </group>
          <mesh
            geometry={nodes.Object_51.geometry}
            material={materials.painting_frame}
            position={[0.001, -0.01, -0.049]}
            rotation={[0, -1.571, 0]}
            scale={0.319}
          >
            <meshBasicMaterial
              map={texture}
              polygonOffset
              polygonOffsetFactor={-1}
            />
          </mesh>
          {props.mode === "first person" ? (
            props.isClose && (
              <>
                <mesh
                  ref={octahedronGeometryRef}
                  position={[0.7, 0.44, 0.05]}
                  onClick={() => {
                    if (props.mode === "first person") return;
                    props.onShowPanel(props.item);
                  }}
                >
                  <octahedronGeometry args={[0.08, 0]} />
                  <meshNormalMaterial />
                </mesh>
                {!props.isOpen && (
                  <Html
                    position={[1, 0.44, 0.05]}
                    center
                    style={{
                      color: "white",
                      fontSize: "14px",
                      textAlign: "center",
                      background: "rgba(0, 0, 0, 0.7)",
                      padding: "5px",
                      width: "120px",
                      borderRadius: "5px",
                      pointerEvents: "none",
                    }}
                  >
                    Nhấn E để xem chi tiết
                  </Html>
                )}
              </>
            )
          ) : (
            <mesh
              ref={octahedronGeometryRef}
              position={[0.7, 0.44, 0.05]}
              onClick={() => {
                if (props.mode === "first person") return;
                props.onShowPanel(props.item);
              }}
            >
              <octahedronGeometry args={[0.06, 0]} />
              <meshNormalMaterial />
            </mesh>
          )}
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(
  "https://firebasestorage.googleapis.com/v0/b/artchain-c46a7.firebasestorage.app/o/3D-models%2Fpainting_frame.glb?alt=media&token=5b003fdd-bd8e-4313-ac5d-562ce8ab002b"
);
