/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\chibi_guy\scene.gltf -t -r public 
Author: Seb00927 (https://sketchfab.com/Seb00927)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/chibi-guy-d29d0100874641c58a8ba4ebdf3b5e65
Title: Chibi Guy
*/

import * as THREE from "three";
import React, { JSX, useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF, SkeletonUtils } from "three-stdlib";

type ActionName = "0Tpose" | "Clapping" | "Idle" | "Run" | "Surprise" | "Walk";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    Object_7: THREE.SkinnedMesh;
    Object_8: THREE.SkinnedMesh;
    Object_9: THREE.SkinnedMesh;
    Object_10: THREE.SkinnedMesh;
    Object_11: THREE.SkinnedMesh;
    Object_12: THREE.SkinnedMesh;
    GLTF_created_0_rootJoint: THREE.Bone;
  };
  materials: {
    Eyes: THREE.MeshStandardMaterial;
    Uniform_Blue: THREE.MeshStandardMaterial;
    Uniform_Black: THREE.MeshStandardMaterial;
    Uniform_White: THREE.MeshStandardMaterial;
    ["Skin.001"]: THREE.MeshStandardMaterial;
    ["Hair.001"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

interface ChibiGuyProps {
  animation?: ActionName;
  hairColor?: string;
  skinColor?: string;
}

export default function ChibiGuy({
  animation = "Idle",
  hairColor,
  skinColor,
  ...props
}: JSX.IntrinsicElements["group"] & ChibiGuyProps) {
  const group = React.useRef<THREE.Group>(null);
  const { scene, animations } = useGLTF("/chibi_guy/scene.gltf");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (animation) {
      actions[animation]?.reset().fadeIn(0.5).play();
    }
    return () => {
      if (animation) {
        actions[animation]?.fadeOut(0.5);
      }
    };
  }, [animation, actions]);
  return (
    <group
      ref={group}
      scale={0.6}
      {...props}
      position={[0, -0.8, 0]}
      dispose={null}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Armature_23" position={[0, 0.495, 0]}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="Left_eye_22" />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Eyes}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials.Uniform_Blue}
                    skeleton={nodes.Object_8.skeleton}
                  />
                  <skinnedMesh
                    name="Object_9"
                    geometry={nodes.Object_9.geometry}
                    material={materials.Uniform_Black}
                    skeleton={nodes.Object_9.skeleton}
                  />
                  <skinnedMesh
                    name="Object_10"
                    geometry={nodes.Object_10.geometry}
                    material={materials.Uniform_White}
                    skeleton={nodes.Object_10.skeleton}
                  />
                  <skinnedMesh
                    name="Object_11"
                    geometry={nodes.Object_11.geometry}
                    material={materials["Skin.001"]}
                    skeleton={nodes.Object_11.skeleton}
                  >
                    <meshStandardMaterial
                      color={skinColor ?? materials["Skin.001"].color}
                    />
                  </skinnedMesh>
                  <skinnedMesh
                    name="Object_12"
                    geometry={nodes.Object_12.geometry}
                    material={materials["Hair.001"]}
                    skeleton={nodes.Object_12.skeleton}
                  >
                    <meshStandardMaterial
                      color={hairColor ?? materials["Hair.001"].color}
                    />
                  </skinnedMesh>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/chibi_guy/scene.gltf");
