/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\client\public\dienbienphu.glb --transform -t -r public 
Files: .\client\public\dienbienphu.glb [104.51MB] > D:\Works\Coding-Stuffs\3D\vnr-exhibition\dienbienphu-transformed.glb [4.6MB] (96%)
*/

import { Html, useGLTF } from "@react-three/drei";
import { ThreeEvent, useFrame } from "@react-three/fiber";
import { JSX, useRef } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import { CameraMovementOptions } from "../hooks/useCameraMovement";
import { Data } from "../app/(exhibition)/page";

type GLTFResult = GLTF & {
  nodes: {
    material: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
  };
};

interface DienBienPhuModelProps {
  onMoveCamera?: (
    object: THREE.Object3D,
    options?: CameraMovementOptions
  ) => void;
  onShowPanel: (item: Data) => void;
  showIcon: boolean;
  item: Data;
  mode?: string;
  isClose?: boolean;
  isOpen?: boolean;
}

export default function DienBienPhuModel({
  onClick,
  onContextMenu,
  onPointerOver,
  onPointerOut,
  ...props
}: JSX.IntrinsicElements["group"] & DienBienPhuModelProps) {
  const { nodes, materials } = useGLTF(
    "/dienbienphu-transformed.glb"
  ) as unknown as GLTFResult;
  const groupRef = useRef<THREE.Group>(null);
  const octahedronGeometryRef = useRef<THREE.Mesh>(null);
  useFrame((_, delta) => {
    if (octahedronGeometryRef.current) {
      octahedronGeometryRef.current.rotation.y += delta;
    }
  });

  return (
    <group {...props} ref={groupRef} dispose={null}>
      <mesh
        geometry={nodes.material.geometry}
        material={materials["Material.001"]}
        rotation={[Math.PI / 2, 0, 0]}
        onClick={(e) => {
          if (props.mode === "first person") return;
          e.stopPropagation();
          if (props.onMoveCamera && groupRef.current) {
            props.onMoveCamera(groupRef.current, {
              offsetX: -2,
              offsetZ: 0.2,
              offsetY: 1.2,
            });
          }
          if (onClick) {
            (onClick as (event: ThreeEvent<MouseEvent>) => void)(e);
          }
        }}
        onPointerOver={onPointerOver}
        onPointerOut={onPointerOut}
      />
      {props.mode !== "camera" ? (
        props.isClose && (
          <>
            <mesh
              ref={octahedronGeometryRef}
              position={[0.7, 0.44, 0.05]}
              onClick={(e) => {
                e.stopPropagation;
                if (props.mode !== "camera") return;
                props.onShowPanel(props.item);
              }}
            >
              <octahedronGeometry args={[0.1, 0]} />
              <meshNormalMaterial />
            </mesh>
            {!props.isOpen && (
              <>
                <Html
                  position={[1, 0.44, 0.05]}
                  center
                  style={{
                    color: "white",
                    fontSize: "14px",
                    textAlign: "center",
                    background: "rgba(0, 0, 0, 0.7)",
                    padding: "5px",
                    width: "120px",
                    borderRadius: "5px",
                    pointerEvents: "none",
                  }}
                >
                  Nhấn E để xem chi tiết
                </Html>
                <Html
                  position={[-0.9, 0.55, 0.05]}
                  center
                  style={{
                    color: "white",
                    fontSize: "14px",
                    textAlign: "center",
                    background: "rgba(0, 0, 0, 0.7)",
                    padding: "5px",
                    width: "120px",
                    borderRadius: "5px",
                    pointerEvents: "none",
                  }}
                >
                  {props.item.title}
                </Html>
              </>
            )}
          </>
        )
      ) : (
        <mesh
          ref={octahedronGeometryRef}
          position={[0.5, 0.22, 0.05]}
          onClick={() => {
            if (props.mode !== "camera") return;
            props.onShowPanel(props.item);
          }}
        >
          <octahedronGeometry args={[0.06, 0]} />
          <meshNormalMaterial />
        </mesh>
      )}
    </group>
  );
}

useGLTF.preload("/dienbienphu-transformed.glb");
