/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\client\public\dienbienphu.glb --transform -t -r public 
Files: .\client\public\dienbienphu.glb [104.51MB] > D:\Works\Coding-Stuffs\3D\vnr-exhibition\dienbienphu-transformed.glb [4.6MB] (96%)
*/

import { Html, useGLTF } from "@react-three/drei";
import { ThreeEvent, useFrame } from "@react-three/fiber";
import { JSX, useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import { CameraMovementOptions } from "../hooks/useCameraMovement";
import { Data } from "../app/(exhibition)/page";

type GLTFResult = GLTF & {
  nodes: {
    material: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
  };
};

interface DienBienPhuModelProps {
  onMoveCamera?: (
    object: THREE.Object3D,
    options?: CameraMovementOptions
  ) => void;
  onShowPanel: (item: Data) => void;
  item: Data;
  mode?: string;
  isClose?: boolean;
  isOpen?: boolean;
}

export default function DienBienPhuModel({
  onClick,
  onPointerOver,
  onPointerOut,
  ...props
}: JSX.IntrinsicElements["group"] & DienBienPhuModelProps) {
  const { nodes, materials } = useGLTF(
    "/dienbienphu-transformed.glb"
  ) as unknown as GLTFResult;
  const groupRef = useRef<THREE.Group>(null);
  const octahedronGeometryRef = useRef<THREE.Mesh>(null);
  useFrame((_, delta) => {
    if (octahedronGeometryRef.current) {
      octahedronGeometryRef.current.rotation.y += delta;
    }
  });

  return (
    <group {...props} ref={groupRef} dispose={null}>
      <mesh
        geometry={nodes.material.geometry}
        material={materials["Material.001"]}
        rotation={[Math.PI / 2, 0, 0]}
        raycast={() => null}
      />
      {props.mode !== "camera" ? (
        props.isClose && (
          <>
            <mesh
              ref={octahedronGeometryRef}
              position={[0.7, 0.44, 0.05]}
              onClick={(e) => {
                e.stopPropagation;
                if (props.mode !== "camera") return;
                props.onShowPanel(props.item);
              }}
            >
              <octahedronGeometry args={[0.1, 0]} />
              <meshNormalMaterial />
            </mesh>

            {!props.isOpen && (
              <>
                <Html
                  position={[0.44, 0.22, 0.05]}
                  center
                  style={{
                    color: "black",
                    fontSize: "14px",
                    textAlign: "center",
                    background: "white",
                    padding: "5px",
                    width: "120px",
                    borderRadius: "5px",
                    pointerEvents: "none",
                  }}
                >
                  Nhấn E để xem chi tiết
                </Html>
                <Html
                  position={[-0.44, 0.22, 0.05]}
                  center
                  style={{
                    color: "black",
                    fontSize: "14px",
                    textAlign: "center",
                    background: "white",
                    padding: "5px",
                    width: "120px",
                    borderRadius: "5px",
                    pointerEvents: "none",
                  }}
                >
                  {props.item.title}
                </Html>
              </>
            )}
          </>
        )
      ) : (
        <>
          <mesh
            ref={octahedronGeometryRef}
            position={[0.5, 0.22, 0.05]}
            onClick={(e) => {
              if (props.mode !== "camera") return;
              e.stopPropagation();
              props.onShowPanel(props.item);
            }}
            onPointerOver={onPointerOver}
            onPointerOut={onPointerOut}
          >
            <octahedronGeometry args={[0.06, 0]} />
            <meshNormalMaterial />
          </mesh>
          <mesh
            onClick={(e) => {
              if (props.mode !== "camera") return;
              e.stopPropagation();
              if (props.onMoveCamera && groupRef.current) {
                props.onMoveCamera(groupRef.current, {
                  offsetX: -1,
                  offsetY: 0.2,
                  zoom: 1.2,
                });
              }
              if (onClick) {
                (onClick as (event: ThreeEvent<MouseEvent>) => void)(e);
              }
            }}
            onPointerOver={onPointerOver}
            onPointerOut={onPointerOut}
            position={[0, 0.05, 0]}
            visible={false}
          >
            <boxGeometry args={[0.75, 0.1, 0.75]} />
            <meshStandardMaterial color="red" />
          </mesh>
        </>
      )}

      {!props.isOpen && (
        <Html
          position={[0, 0, 0.05]}
          center
          style={{
            pointerEvents: "none",
          }}
        >
          <div
            style={{
              width: "24px",
              height: "24px",
              borderRadius: "50%",
              background: "rgba(255, 255, 255, 0.8)",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              fontSize: "12px",
              fontWeight: "bold",
              color: "black",
              border: "1px solid black",
            }}
          >
            {props.item.id}
          </div>
        </Html>
      )}
    </group>
  );
}

useGLTF.preload("/dienbienphu-transformed.glb");
