/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\client\public\circle.glb --transform -t -r public 
Files: .\client\public\circle.glb [81.92MB] > D:\Works\Coding-Stuffs\3D\vnr-exhibition\circle-transformed.glb [2.28MB] (97%)
*/

import * as THREE from "three";
import React, { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    CeillingWire_CeillingWire_0: THREE.Mesh;
    Lamp_Emissive_0: THREE.Mesh;
    Lamp_Lamp_0: THREE.Mesh;
    Walls_Ceilling_0: THREE.Mesh;
    Walls_Floor_0: THREE.Mesh;
    Walls_Walls_0: THREE.Mesh;
  };
  materials: {
    CeillingWire: THREE.MeshStandardMaterial;
    Emissive: THREE.MeshStandardMaterial;
    Lamp: THREE.MeshStandardMaterial;
    Ceilling: THREE.MeshStandardMaterial;
    Floor: THREE.MeshStandardMaterial;
    Walls: THREE.MeshStandardMaterial;
  };
};

export default function ExhibitionModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/circle-transformed.glb"
  ) as unknown as GLTFResult;
  //   materials.Emissive.emissive = new THREE.Color(1, 1, 1); // White emissive for glow
  //   materials.Emissive.emissiveIntensity = 1; // Intensity of emission
  //   materials.Walls.emissive = new THREE.Color(1, 1, 1); // Subtle emissive for walls
  //   materials.Walls.emissiveIntensity = 1;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.CeillingWire_CeillingWire_0.geometry}
        material={materials.CeillingWire}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.5, 0.5, 0.225]}
      />
      <mesh
        geometry={nodes.Lamp_Emissive_0.geometry}
        material={materials.Emissive}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Lamp_Lamp_0.geometry}
        material={materials.Lamp}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Walls_Ceilling_0.geometry}
        material={materials.Ceilling}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.5, 0.5, 0.225]}
      />
      <mesh
        geometry={nodes.Walls_Floor_0.geometry}
        material={materials.Floor}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.5, 0.5, 0.225]}
      />
      <mesh
        geometry={nodes.Walls_Walls_0.geometry}
        material={materials.Walls}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.5, 0.5, 0.225]}
      />
    </group>
  );
}

useGLTF.preload("/circle-transformed.glb");
