/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\client\public\frames\painting_frame.glb --transform -t -r public 
Files: .\client\public\frames\painting_frame.glb [107.03MB] > D:\Works\Coding-Stuffs\3D\vnr-exhibition\painting_frame-transformed.glb [4.44MB] (96%)
*/

import { Html, useGLTF, useTexture } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { JSX, useRef } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import { Data } from "../app/(exhibition)/page";

type GLTFResult = GLTF & {
  nodes: {
    Object_10: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_51: THREE.Mesh;
  };
  materials: {
    ["Material.028"]: THREE.MeshStandardMaterial;
    ["Material.029"]: THREE.MeshStandardMaterial;
    painting_frame: THREE.MeshStandardMaterial;
  };
};

interface PaintingFrameTransformedProps {
  onMoveCamera?: (object: THREE.Object3D) => Promise<void>;
  onShowPanel: (item: Data) => void;
  showIcon: boolean;
  item: Data;
  mode?: string;
  isClose?: boolean;
  isOpen?: boolean;
}

export default function PaintingFrameTransformed(
  props: JSX.IntrinsicElements["group"] & PaintingFrameTransformedProps
) {
  const { nodes, materials } = useGLTF(
    "/painting_frame-transformed.glb"
  ) as unknown as GLTFResult;
  const groupRef = useRef<THREE.Group>(null);
  const texture = useTexture(props.item.imageUrl);
  const octahedronGeometryRef = useRef<THREE.Mesh>(null);

  useFrame((_, delta) => {
    if (octahedronGeometryRef.current) {
      octahedronGeometryRef.current.rotation.y += delta;
      octahedronGeometryRef.current.rotation.x += delta * 0.3;
    }
  });
  return (
    <group
      {...props}
      ref={groupRef}
      dispose={null}
      onClick={() => {
        if (props.onMoveCamera && groupRef.current) {
          props.onMoveCamera(groupRef.current);
        }
      }}
    >
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials["Material.028"]}
        position={[0.001, 1.161, -0.076]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.494}
      />
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["Material.029"]}
        position={[0.001, 1.161, -0.076]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.494}
      />
      <mesh
        geometry={nodes.Object_51.geometry}
        material={materials.painting_frame}
        position={[0.001, 1.161, -0.076]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.494}
      >
        <meshBasicMaterial
          map={texture}
          polygonOffset
          polygonOffsetFactor={-1}
        />
      </mesh>
      {props.mode === "first person" ? (
        props.isClose && (
          <>
            <mesh
              ref={octahedronGeometryRef}
              position={[0.7, 0.44, 0.05]}
              onClick={() => {
                if (props.mode === "first person") return;
                props.onShowPanel(props.item);
              }}
            >
              <octahedronGeometry args={[0.08, 0]} />
              <meshNormalMaterial />
            </mesh>
            {!props.isOpen && (
              <Html
                position={[1, 0.44, 0.05]}
                center
                style={{
                  color: "white",
                  fontSize: "14px",
                  textAlign: "center",
                  background: "rgba(0, 0, 0, 0.7)",
                  padding: "5px",
                  width: "120px",
                  borderRadius: "5px",
                  pointerEvents: "none",
                }}
              >
                Nhấn E để xem chi tiết
              </Html>
            )}
          </>
        )
      ) : (
        <mesh
          ref={octahedronGeometryRef}
          position={[0.7, 0.44, 0.05]}
          onClick={() => {
            if (props.mode === "first person") return;
            props.onShowPanel(props.item);
          }}
        >
          <octahedronGeometry args={[0.06, 0]} />
          <meshNormalMaterial />
        </mesh>
      )}
    </group>
  );
}

useGLTF.preload("/../painting_frame-transformed.glb");
